version: "3"
services:
  app:
    image: practica_docker
    ports:
      - "8000:8000"
    environment:
      - CON_STRING_CLOUD='mongodb+srv://ChrisAqM:9yBkG1RQTxKRZZ45@cluster0.jp8ivfz.mongodb.net/?retryWrites=true&w=majority'
    depends_on:
      - db
  db:
    image: mongo

